remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
title: Four Short Links # name of the site
author: 4shortlinks courtesy Nat Torkington # name of site's author
url: https://4shortlinks.e-work.xyz # root address of the site
# baseurl: "/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
tagline: Nat Torkington’s eclectic collection of curated links.
description: > # description of the site (multiple lines allowed)
  Nat Torkington’s eclectic collection of curated links. O'Reilly Radar's Four Short Links is retired (jan2021) but you can sometimes find '4 or more links' here.

social:
  name: 4shortlinks
  links:
    - https://twitter.com/4shortlinks

twitter:
  username: 4shortlinks

defaults:
  - scope:
      path: ""
    values:
      image: /4sl-xdisplay-logo-400px-circle.png

feed:
  path: feedroll.xml

permalink: /:year-:month-:day-:slug.html

favicon: "4sl-xdisplay-logo-400px-circle.png" # name+extension of favicon (which must be put on the root folder)
logo: "4sl-xdisplay-logo-400px-circle.png"

goat_counter: G-MS54XJ8XZ5 # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%B %-d, %Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag